<?php
/*
 * results as separate value in response.
 *
 * @param array $output
 *   Results of the view execution. These will be sent to services for renderin$
 * @param object $view
 *   Views object.
 */
function services_views_totals_services_views_execute_view_alter(&$output, $view) {
     $total_results = $view->total_rows;
     $page_results = count($view->result);
     $current_page = $view->query->pager->current_page;
     $items_per_page = $view->get_items_per_page();
     $total_pages = $total_results/$items_per_page-1;
     $start = ($current_page) * $items_per_page + 1;
     $end = $start+$page_results-1;	
 
     $paged_output = array(
      'metadata' => array(
	 'current_page' => $current_page,
	 'total_pages' => ceil($total_pages),
         'items_per_page' => $items_per_page,
	 'display_start' => $start,
         'display_end' => $end,
	 'total_results' => $total_results),
      'results' => $output

    );
    $output = $paged_output;
}

?>
